In [4]:
#Importing pandas and numpy python library
import pandas as pd
import numpy as np

# Reading the datasets from the .csv files into pandas Dataframe
netflix = pd.read_csv("netflix_titles.csv")
prime = pd.read_csv("amazon_prime_titles.csv")
disney = pd.read_csv("disney_plus_titles.csv")
hulu = pd.read_csv("hulu_titles.csv")

# Adding a new column of platform for each of the dataset with its platform name
netflix["platform"] = "Netflix"
prime["platform"] = "Amazon Prime"
disney["platform"] = "Disney+"
hulu["platform"] = "Hulu"

# Merging all 4 datasets into one and removing the index values, Then performing data cleaning and 
# data wrangling operations to clean and arrange the dataset
combined_df1 = pd.concat([netflix, prime, disney, hulu], ignore_index=True)
combined_df1.to_excel('combined_dataset.xlsx', index=False)
print(combined_df1.columns,'\n\n')

#Considering only the required variables from the dataframe
combined_df = combined_df1[['type','title','release_year','platform','date_added']].copy()

#Changing the format of the date in date_added column along with stripping off the leading and trailing spaces
#to avoid error
combined_df['title'] = combined_df['title'].str.strip()
combined_df['date_added'] = combined_df['date_added'].str.strip()
combined_df['date_added'] = pd.to_datetime(combined_df['date_added'], format='%B %d, %Y')

#Sorting the dataset based on the type of the content, movie/tvshows
combined_df = combined_df.sort_values(['type']).reset_index()
combined_df = combined_df.drop(['index'],axis=1)
combined_df.to_excel('combined_cleaned.xlsx', index=False)
print(combined_df.dtypes,'\n\n')
print(combined_df.info(),'\n\n',combined_df.isnull().sum())

#getting Unique values in all columns
type_unique = combined_df['type'].unique()
release_year_unique = combined_df['release_year'].unique()
platform_unique = combined_df['platform'].unique()
    
print(type_unique,release_year_unique,platform_unique)

#Creating a sample of the large dataset for test runs
test_run = combined_df.iloc[:500]
test_run.to_excel('Book1.xlsx',index=False)

combined_df

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'platform'],
      dtype='object')


type                    object
title                   object
release_year             int64
platform                object
date_added      datetime64[ns]
dtype: object


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22998 entries, 0 to 22997
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   type          22998 non-null  object
 1   title         22998 non-null  object
 2   release_year  22998 non-null  int64
 3   platform      22998 non-null  object
 4   date_added    13444 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 898.5+ KB
None

 type               0
title              0
release_year       0
platform           0
date_added      9554
dtype: int64
['Movie' 'TV Show'] [2020 2014 2015 2019 2016 1988 2018 1997 1973 1964 2021 2017 2007 2013
 1942 1991 1992 2012 1989 2002 1987 1984 2005 1976 2006 2003 2011 2004
 1993 2009 1995 1979 1994 2010 2008 1982 1981 1952 2001 1967 1998 1990
 1996 2000 1955 1927 1968 1950 1949 1999 1959 1986 1969 1945 1930 1985
 1962 1947 1958 1978 1963 1956 1971 1974 1983 1965 1926 1941 1946 1932
 1951 1975 1977 1957 1953 1938 1972 1940 1943 1961 1954 1966 1925 1936
 1980 1970 1960 1948 1934 1939 1937 1935 1929 1933 1944 1931 1920 1922
 1924 1923 1928] ['Netflix' 'Amazon Prime' 'Disney+' 'Hulu']

,type,title,release_year,platform,date_added
0,Movie,Dick Johnson Is Dead,2020,Netflix,2021-09-25
1,Movie,The Truth About Emanuel,2014,Amazon Prime,NaT
2,Movie,Tooth Fairy 2: The Root of Evil,2020,Amazon Prime,NaT
3,Movie,Trumbo,2015,Amazon Prime,NaT
4,Movie,Yakov Smirnoff: United We Laugh,2020,Amazon Prime,NaT
...,...,...,...,...,...
22993,TV Show,The Haunting of Hill House,2018,Netflix,2018-10-12
22994,TV Show,Ordinary Heroes,2018,Netflix,2018-10-11
22995,TV Show,Salt Fat Acid Heat,2018,Netflix,2018-10-11
22996,TV Show,Marvel's Daredevil,2018,Netflix,2018-10-19
22997,TV Show,Tokyo Magnitude 8.0,2009,Hulu,NaT

In [1]:
%%time
#For a movie
import imdb

#Creating a class instance of IMDB
ia = imdb.IMDb()

title = "Trumbo"
#Created an API call to search for the movie.
title_search = ia.search_movie(title)
title1 = title_search[0]
ID_imdb = title1.getID()

movie_data = ia.get_movie(ID_imdb)
print(movie_data.keys(),'\n')

#Retreiving the desired outputs
rating_imdb = ia.get_movie(ID_imdb)['rating']
genre_imdb = ia.get_movie(ID_imdb)['genres']
runtime_imdb = ia.get_movie(ID_imdb)['runtimes']
director_imdb = ia.get_movie(ID_imdb)['director']
countries_imdb = ia.get_movie(ID_imdb)['countries']
votes_imdb = ia.get_movie(ID_imdb)['votes']
certificates_imdb = ia.get_movie(ID_imdb)['certificates']

['localized title', 'cast', 'genres', 'runtimes', 'countries', 'country codes', 'language codes', 'color info', 'aspect ratio', 'sound mix', 'box office', 'certificates', 'original air date', 'rating', 'votes', 'cover url', 'imdbID', 'videos', 'plot outline', 'languages', 'title', 'year', 'kind', 'original title', 'director', 'writer', 'producer', 'composer', 'cinematographer', 'editor', 'editorial department', 'casting director', 'production design', 'art direction', 'set decoration', 'costume designer', 'make up', 'production manager', 'assistant director', 'art department', 'sound crew', 'special effects', 'visual effects', 'stunt performer', 'camera and electrical department', 'casting department', 'costume department', 'location management', 'music department', 'script department', 'transportation department', 'miscellaneous crew', 'thanks', 'akas', 'production companies', 'distributors', 'special effects companies', 'other companies', 'canonical title', 'long imdb title', 'long imdb canonical title', 'smart canonical title', 'smart long imdb canonical title', 'full-size cover url']

CPU times: user 1.41 s, sys: 123 ms, total: 1.53 s
Wall time: 15.2 s

In [2]:
print(title_search,'\n')
print(title1,'\n')
print('IMDB ID:'ID_imdb,'\n',type(ID_imdb),'\n')
ID_imdb = float(ID_imdb)
print(ID_imdb,'\n',type(ID_imdb),'\n')
print(rating_imdb,'\n',type(rating_imdb),'\n')
print(genre_imdb,'\n',type(genre_imdb),'\n')
print(runtime_imdb[0],'\n',type(runtime_imdb),'\n')
print(director_imdb[0],'\n',type(director_imdb),'\n')
print(countries_imdb,'\n',type(countries_imdb),'\n')
print(votes_imdb,'\n',type(votes_imdb),'\n')
print(certificates_imdb,'\n',type(certificates_imdb),'\n')
print(type(movie_data),'\n')
print(ia.get_movie(ID_imdb)['kind'])

[<Movie id:3203606[http] title:_Trumbo (None)_>, <Movie id:0889671[http] title:_Trumbo (None)_>, <Movie id:0120382[http] title:_The Truman Show (None)_>, <Movie id:5244894[http] title:_Dalton Trumbo: From A-List to Blacklist (None)_>, <Movie id:0926288[http] title:_Dalton Trumbo: Rebel in Hollywood (None)_>, <Movie id:0067277[http] title:_Johnny Got His Gun (None)_>, <Movie id:0462499[http] title:_Rambo (None)_>, <Movie id:0060028[http] title:_Star Trek (None)_>, <Movie id:3861390[http] title:_Dumbo (None)_>, <Movie id:1206885[http] title:_Rambo: Last Blood (None)_>, <Movie id:0033563[http] title:_Dumbo (None)_>, <Movie id:0095956[http] title:_Rambo III (None)_>, <Movie id:0109508[http] title:_Crumb (None)_>, <Movie id:0114733[http] title:_Tromeo and Juliet (None)_>, <Movie id:3754940[http] title:_Truman (None)_>, <Movie id:0222619[http] title:_Rambo (None)_>, <Movie id:13144040[http] title:_Rumbo: First Pee (None)_>, <Movie id:0089880[http] title:_Rambo: First Blood Part II (None)_>, <Movie id:5223624[http] title:_Parallel Roads (None)_>, <Movie id:2328813[http] title:_Hard to Be a God (None)_>]

Trumbo

3203606
 <class 'str'>

3203606.0
 <class 'float'>

7.4
 <class 'float'>

['Biography', 'Drama']
 <class 'list'>

124
 <class 'list'>

Jay Roach
 <class 'list'>

['United States']
 <class 'list'>

82877
 <class 'int'>

['Argentina:Atp::(with warning)', 'Australia:M', 'Brazil:12', 'Canada:14A::(Alberta)', 'Canada:PG::(British Columbia)', 'Chile:14', 'Finland:K-7', 'France:Tous publics', 'Germany:6', 'Hong Kong:IIA', 'Ireland:15A', 'Israel:ALL', 'Italy:T', 'Japan:G', 'Lithuania:N-16', 'Malta:12', 'Netherlands:AL', 'New Zealand:M', 'Norway:A::(cinema rating)', 'Philippines:R-13', 'Poland:12::(TV rating)', 'Portugal:M/12', 'Russia:18+', 'Singapore:PG13', 'South Africa:13', 'South Africa:16::(DVD rating)', 'South Korea:15', 'Spain:7', 'Sweden:15', 'Switzerland:12', 'Taiwan:GP', 'United Kingdom:15', 'United States:R']
 <class 'list'>

<class 'imdb.Movie.Movie'>

movie

In [6]:
%%time
#Creating a function to request all desired data once at a time instead of multiple different requests
def IMDB_info(title, info_type):
    ia = imdb.IMDb()
    title_search = ia.search_movie(title)
    if title_search:
        title1 = title_search[0]
        ID_imdb = title1.getID()
        movie = ia.get_movie(ID_imdb)
        if info_type in movie: 
            info = movie[info_type]
        else:
            info = None
        return info

CPU times: user 7 Âµs, sys: 8 Âµs, total: 15 Âµs
Wall time: 25 Âµs

In [5]:
#Considering the test run dataset with only 30 observations
df = pd.read_excel("Book1.xlsx")

In [7]:
%%time
#Using the .apply method to request the IMDB rating of the title which is listed as 'rating' in the IMDB database
df['IMDB Rating'] = df["title"].apply(IMDB_info,info_type = "rating")

CPU times: user 1min 15s, sys: 5.83 s, total: 1min 21s
Wall time: 27min 18s

In [8]:
%%time
#Using the .apply method to request the Genre of the title which is listed as 'genres' in the IMDB database
df['Genre'] = df["title"].apply(IMDB_info,info_type = "genres")

2023-04-24 18:50:02,605 CRITICAL [imdbpy] /Users/ruthwiknadam/opt/anaconda3/lib/python3.9/site-packages/imdb/_exceptions.py:32: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Without+a+Paddle%3A+Nature%27s+Calling&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')},); kwds: {}
Traceback (most recent call last):
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 233, in retrieve_unicode
    response = uopener.open(url)
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/ruthwiknadam/opt/anaconda3/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find/?q=Without+a+Paddle%3A+Nature%27s+Calling&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': timeout('The read operation timed out')}

In [ ]:
%%time
#Using the .apply method to request the duration of the title which is listed as 'runtimes' in the IMDB database
df['Runtime'] = df["title"].apply(IMDB_info, info_type = "runtimes")

In [ ]:
%%time
#Using the .apply method to request the director of the title which is listed as 'director' in the IMDB database
df['Director'] = df["title"].apply(IMDB_info, info_type = "director")

In [ ]:
%%time
#Using the .apply method to request the IMDB votes of the title which is listed as 'votes' in the IMDB database
df['Votes'] = df["title"].apply(IMDB_info, info_type = "votes")

## Working on smaller dataset

In [6]:
%%time

#Importing required libraries
import pandas as pd
import numpy as np

netflix = pd.read_csv("netflix_titles.csv")

print(netflix.info())

#Dropping all null value rows
#The inplace=True attribute updates the original dataset instead of creating a slice of the data
netflix.dropna(inplace=True)

#Dropping the unnecessary columns from the dataset
if 'show_id' and 'cast' and 'description' in netflix:
    netflix.drop(['show_id','cast','description'],axis=1,inplace=True)

#Filtering the data to consider only the movies released between 2018 to 2021
netflix_filtered = netflix[(netflix['release_year'] >= 2018) & (netflix['release_year'] <= 2021)].copy()

#Filtering the data to consider only the movies
netflix_movies = netflix_filtered[netflix_filtered['type'] == 'Movie'].copy()

#Use str.extract() method to extract the numeric value from each duration string 
#and convert it to a class int using astype()
netflix_movies['duration'] = netflix_movies['duration'].str.extract('(\d+)').astype(int)

#Removing leading and trailing white spaces to avoid incorrect search query
netflix_movies['title'] = netflix_movies['title'].str.strip()

#Sorting the dataset based on the title in ascending order
netflix_movies.sort_values(['title'],inplace=True)

#Renaming all columns in the dataset
netflix_movies.rename(columns={'listed_in':'Genres','type':'Type','title':'Title','director':'Director',
                      'country':'Countries','date_added':'Date Added','release_year':'Release Year',
                       'duration':'Runtime','rating':'Certificate'},inplace=True)

print(netflix_movies.info())
netflix_movies.reset_index(drop=True,inplace=True)
netflix_movies.to_excel('Netflix.xlsx',index=False)
netflix_movies.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1682 entries, 2036 to 4667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          1682 non-null   object
 1   Title         1682 non-null   object
 2   Director      1682 non-null   object
 3   Countries     1682 non-null   object
 4   Date Added    1682 non-null   object
 5   Release Year  1682 non-null   int64
 6   Certificate   1682 non-null   object
 7   Runtime       1682 non-null   int64
 8   Genres        1682 non-null   object
dtypes: int64(2), object(7)
memory usage: 131.4+ KB
None
CPU times: user 991 ms, sys: 1.23 s, total: 2.22 s
Wall time: 692 ms

,Type,Title,Director,Countries,Date Added,Release Year,Certificate,Runtime,Genres
0,Movie,#Alive,Cho Il,South Korea,"September 8, 2020",2020,TV-MA,99,"Horror Movies, International Movies, Thrillers"
1,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto",Italy,"July 1, 2020",2019,TV-14,95,"Documentaries, International Movies"
2,Movie,#FriendButMarried,Rako Prijanto,Indonesia,"May 21, 2020",2018,TV-G,102,"Dramas, International Movies, Romantic Movies"
3,Movie,#FriendButMarried 2,Rako Prijanto,Indonesia,"June 28, 2020",2020,TV-G,104,"Dramas, International Movies, Romantic Movies"
4,Movie,#Roxy,Michael Kennedy,Canada,"April 10, 2019",2018,TV-14,105,"Comedies, Romantic Movies"

In [7]:
%%time
# split the dataframe into smaller dataframes of maximum 300 observations
dfs = [netflix_movies[i:i+300].copy() for i in range(0, len(netflix_movies), 300)]

print(type(dfs))
print(len(dfs))

<class 'list'>
6
CPU times: user 6.87 ms, sys: 3.13 ms, total: 10 ms
Wall time: 7.35 ms

In [11]:
%%time
import imdb

# Create a dictionary to store cached results
cached_results = {}

def IMDB_info(title, info_type):
    global cached_results
    
    # Check if the result is already cached
    if title in cached_results and info_type in cached_results[title]:
        return cached_results[title][info_type]

    # Make a new API call if the result is not cached
    ia = imdb.IMDb()
    title_search = ia.search_movie(title)
    if title_search:
        title1 = title_search[0]
        ID_imdb = title1.getID()
        movie = ia.get_movie(ID_imdb)
        if info_type in movie:
            info = movie[info_type]
            info = 6.0
        else:
            info = None

        # Cache the result for future use
        if title not in cached_results:
            cached_results[title] = {}
        cached_results[title][info_type] = info

        return info
    else:
        return None



def func(input_df):
    #Checking if the input given to the function is a pandas DataFrame or not
    if isinstance(input_df,pd.DataFrame):
        #Using .apply() method to call the IMDB_info function and request the data from IMDb server
        input_df['IMDB_rating'] = input_df['Title'].apply(IMDB_info,info_type = "rating")
        input_df['Votes'] = input_df['Title'].apply(IMDB_info,info_type = "votes")
    else:
        print('The input is not a dataframe')
print('Executed')

Executed
CPU times: user 347 Âµs, sys: 133 Âµs, total: 480 Âµs
Wall time: 397 Âµs

In [165]:
%%time
for i, df in enumerate(dfs):
    func(df)
    #Saving the updated dataframes with IMDB rating and votes into .xlsx files
    df.to_excel(f'sdf_{i+1}.xlsx', index=False)
print('Executed')

Executed
CPU times: user 5min 5s, sys: 36.4 s, total: 5min 41s
Wall time: 1h 48min 51s

In [35]:
import pandas as pd
import numpy as np

#All the updated smaller dataframes from the excel sheets are read into a list of dataframes and concatenated
df = pd.concat(map(pd.read_excel, ['sdf_1.xlsx', 'sdf_2.xlsx','sdf_3.xlsx',
                                   'sdf_4.xlsx','sdf_5.xlsx','sdf_6.xlsx']))

print(df.info(),'\n')

df.dropna(inplace=True)
df.reset_index(drop=True,inplace=True)
print(df.info())

#Writing the final dataframe to a .csv file to use in the exploratory data analysis.
df.to_csv('Netflix_Movies.csv')
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1682 entries, 0 to 181
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          1682 non-null   object
 1   Title         1682 non-null   object
 2   Director      1682 non-null   object
 3   Countries     1682 non-null   object
 4   Date Added    1682 non-null   object
 5   Release Year  1682 non-null   int64
 6   Certificate   1682 non-null   object
 7   Runtime       1682 non-null   int64
 8   Genres        1682 non-null   object
 9   IMDB_rating   1631 non-null   float64
 10  Votes         1631 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 157.7+ KB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1631 entries, 0 to 1630
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          1631 non-null   object
 1   Title         1631 non-null   object
 2   Director      1631 non-null   object
 3   Countries     1631 non-null   object
 4   Date Added    1631 non-null   object
 5   Release Year  1631 non-null   int64
 6   Certificate   1631 non-null   object
 7   Runtime       1631 non-null   int64
 8   Genres        1631 non-null   object
 9   IMDB_rating   1631 non-null   float64
 10  Votes         1631 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 140.3+ KB
None

,Type,Title,Director,Countries,Date Added,Release Year,Certificate,Runtime,Genres,IMDB_rating,Votes
0,Movie,#Alive,Cho Il,South Korea,"September 8, 2020",2020,TV-MA,99,"Horror Movies, International Movies, Thrillers",6.3,42842.0
1,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto",Italy,"July 1, 2020",2019,TV-14,95,"Documentaries, International Movies",6.6,1640.0
2,Movie,#FriendButMarried,Rako Prijanto,Indonesia,"May 21, 2020",2018,TV-G,102,"Dramas, International Movies, Romantic Movies",6.8,751.0
3,Movie,#FriendButMarried 2,Rako Prijanto,Indonesia,"June 28, 2020",2020,TV-G,104,"Dramas, International Movies, Romantic Movies",6.9,341.0
4,Movie,#Roxy,Michael Kennedy,Canada,"April 10, 2019",2018,TV-14,105,"Comedies, Romantic Movies",5.0,337.0

In [36]:
import pandas as pd
import numpy as np

#
df = pd.read_csv('Netflix_Movies.csv')
df.drop(['Unnamed: 0','Type'],axis=1,inplace=True)
df

,Title,Director,Countries,Date Added,Release Year,Certificate,Runtime,Genres,IMDB_rating,Votes
0,#Alive,Cho Il,South Korea,"September 8, 2020",2020,TV-MA,99,"Horror Movies, International Movies, Thrillers",6.3,42842.0
1,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto",Italy,"July 1, 2020",2019,TV-14,95,"Documentaries, International Movies",6.6,1640.0
2,#FriendButMarried,Rako Prijanto,Indonesia,"May 21, 2020",2018,TV-G,102,"Dramas, International Movies, Romantic Movies",6.8,751.0
3,#FriendButMarried 2,Rako Prijanto,Indonesia,"June 28, 2020",2020,TV-G,104,"Dramas, International Movies, Romantic Movies",6.9,341.0
4,#Roxy,Michael Kennedy,Canada,"April 10, 2019",2018,TV-14,105,"Comedies, Romantic Movies",5.0,337.0
...,...,...,...,...,...,...,...,...,...,...
1626,Zoo,Shlok Sharma,India,"July 1, 2018",2018,TV-MA,94,"Dramas, Independent Movies, International Movies",6.6,25309.0
1627,"Â¡Ay, mi madre!",Frank Ariza,Spain,"July 19, 2019",2019,TV-MA,81,"Comedies, International Movies",3.9,446.0
1628,Ã’lÃ²tÅ«rÃ©,Kenneth Gyang,Nigeria,"October 2, 2020",2020,TV-MA,107,"Dramas, International Movies",5.6,842.0
1629,â€‹Goli Soda 2,Vijay Milton,India,"September 15, 2018",2018,TV-14,128,"Action & Adventure, Dramas, International Movies",7.1,923.0
1630,â€‹â€‹Kuch Bheege Alfaaz,Onir,India,"September 1, 2018",2018,TV-14,110,"Dramas, Independent Movies, International Movies",7.4,939.0